/* Generated by Yosys 0.63 (git sha1 3bc26ff4d055adfbba8b424508ab4a36405ffc0b, g++ 15.2.1 -O2 -flto=auto -ffat-lto-objects -fexceptions -fstack-protector-strong -m64 -march=x86-64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -mtls-dialect=gnu2 -fno-omit-frame-pointer -mno-omit-leaf-frame-pointer -fPIC -O3) */

(* src = "Johnson-Counter.v:4.1-12.10" *)
module D_flipflop(reset, clkin, D, Q);
  (* src = "Johnson-Counter.v:5.16-5.21" *)
  input reset;
  wire reset;
  (* src = "Johnson-Counter.v:5.23-5.28" *)
  input clkin;
  wire clkin;
  (* src = "Johnson-Counter.v:5.30-5.31" *)
  input D;
  wire D;
  (* src = "Johnson-Counter.v:6.16-6.17" *)
  output Q;
  reg Q;
  (* src = "Johnson-Counter.v:8.1-11.4" *)
  always @(posedge clkin, negedge reset)
    if (!reset) Q <= 1'h0;
    else Q <= D;
endmodule

(* top =  1  *)
(* src = "Johnson-Counter.v:14.1-43.10" *)
module johnson_counter(clkin, reset, \num_out[0] , \num_out[1] , \num_out[2] , \num_out[3] , \num_out[4] , \num_out[5] , \num_out[6] , \num_out[7] , \num_out[8] , \num_out[9] , \num_out[10] , \num_out[11] , \num_out[12] , \num_out[13] , \num_out[14] , \num_out[15] );
  (* src = "Johnson-Counter.v:15.16-15.21" *)
  input clkin;
  wire clkin;
  (* src = "Johnson-Counter.v:15.23-15.28" *)
  input reset;
  wire reset;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[0] ;
  wire \num_out[0] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[1] ;
  wire \num_out[1] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[2] ;
  wire \num_out[2] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[3] ;
  wire \num_out[3] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[4] ;
  wire \num_out[4] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[5] ;
  wire \num_out[5] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[6] ;
  wire \num_out[6] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[7] ;
  wire \num_out[7] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[8] ;
  wire \num_out[8] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[9] ;
  wire \num_out[9] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[10] ;
  wire \num_out[10] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[11] ;
  wire \num_out[11] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[12] ;
  wire \num_out[12] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[13] ;
  wire \num_out[13] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[14] ;
  wire \num_out[14] ;
  (* src = "Johnson-Counter.v:16.24-16.31" *)
  output \num_out[15] ;
  wire \num_out[15] ;
  (* src = "Johnson-Counter.v:22.8-22.25" *)
  wire _0_;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[0] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[10] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[11] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[12] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[13] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[14] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[15] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[1] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[2] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[3] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[4] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[5] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[6] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[7] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[8] ;
  (* src = "Johnson-Counter.v:18.13-18.25" *)
  wire \out_internal[9] ;
  assign _0_ = ~ (* src = "Johnson-Counter.v:22.8-22.25" *) \out_internal[15] ;
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:19.12-24.2" *)
  D_flipflop LSB (
    .D(_0_),
    .Q(\out_internal[0] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:37.12-42.2" *)
  D_flipflop MSB (
    .D(\out_internal[14] ),
    .Q(\out_internal[15] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[10].MID  (
    .D(\out_internal[9] ),
    .Q(\out_internal[10] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[11].MID  (
    .D(\out_internal[10] ),
    .Q(\out_internal[11] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[12].MID  (
    .D(\out_internal[11] ),
    .Q(\out_internal[12] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[13].MID  (
    .D(\out_internal[12] ),
    .Q(\out_internal[13] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[14].MID  (
    .D(\out_internal[13] ),
    .Q(\out_internal[14] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[1].MID  (
    .D(\out_internal[0] ),
    .Q(\out_internal[1] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[2].MID  (
    .D(\out_internal[1] ),
    .Q(\out_internal[2] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[3].MID  (
    .D(\out_internal[2] ),
    .Q(\out_internal[3] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[4].MID  (
    .D(\out_internal[3] ),
    .Q(\out_internal[4] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[5].MID  (
    .D(\out_internal[4] ),
    .Q(\out_internal[5] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[6].MID  (
    .D(\out_internal[5] ),
    .Q(\out_internal[6] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[7].MID  (
    .D(\out_internal[6] ),
    .Q(\out_internal[7] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[8].MID  (
    .D(\out_internal[7] ),
    .Q(\out_internal[8] ),
    .clkin(clkin),
    .reset(reset)
  );
  (* module_not_derived = 32'd1 *)
  (* src = "Johnson-Counter.v:28.20-33.10" *)
  D_flipflop \counter[9].MID  (
    .D(\out_internal[8] ),
    .Q(\out_internal[9] ),
    .clkin(clkin),
    .reset(reset)
  );
  assign \num_out[15]  = \out_internal[15] ;
  assign \num_out[14]  = \out_internal[14] ;
  assign \num_out[13]  = \out_internal[13] ;
  assign \num_out[12]  = \out_internal[12] ;
  assign \num_out[11]  = \out_internal[11] ;
  assign \num_out[10]  = \out_internal[10] ;
  assign \num_out[9]  = \out_internal[9] ;
  assign \num_out[8]  = \out_internal[8] ;
  assign \num_out[7]  = \out_internal[7] ;
  assign \num_out[6]  = \out_internal[6] ;
  assign \num_out[5]  = \out_internal[5] ;
  assign \num_out[4]  = \out_internal[4] ;
  assign \num_out[3]  = \out_internal[3] ;
  assign \num_out[2]  = \out_internal[2] ;
  assign \num_out[1]  = \out_internal[1] ;
  assign \num_out[0]  = \out_internal[0] ;
endmodule
